# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hannah's Winter Wonderland
email: enquiries@discoverhannahs.org
description: > # this means to ignore newlines until "baseurl:"
  For the first time ever, the Edwardian Quad at Hannahs is being transformed into a Winter Wonderland, with a 12m x 15m skating rink, a giant 50 foot snowman (with a bouncy castle in his stomach!), pop-up gift and food stalls, musical Christmas light shows and even regular snow showers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.winterwonderland.org.uk" # the base hostname & protocol for your site
twitter_username: discoverhannahs
github_username:  discoverhannahs

# Build settings
markdown: kramdown

collections:
  sections:
    output: false
  activities:
    output: false
  events:
    output: false
